export default {
  neutral: "Use a balanced, impartial, and objective tone that avoids emotional bias.",
  candid: "Be open, straightforward, and truthful, without sugar-coating the message.",
  optimistic: "Project positivity, hope, and a sense of possibility in your tone.",
  lithe: "Adopt a light, graceful, and effortlessly flowing tone that feels nimble and adaptable.",
  confident: "Communicate with self-assuredness, authority, and conviction.",
  casual: "Maintain an informal, relaxed, and approachable tone.",
  conversational: "Engage the reader with a friendly, natural, and dialogue-like tone.",
  friendly: "Radiate warmth, approachability, and kindness in your tone.",
  professional: "Uphold a respectful, polished, and business-oriented tone.",
  enthusiastic: "Convey energy, excitement, and passion in your tone.",
  empathetic: "Demonstrate understanding, compassion, and emotional sensitivity.",
  humorous: "Inject humor, wit, and lightheartedness to entertain and amuse.",
  inspirational: "Motivate and uplift by appealing to aspirations and positive emotions.",
  assertive: "Express ideas firmly and confidently while respecting boundaries.",
  informative: "Focus on delivering clear, concise, and fact-based educational content.",
  persuasive: "Use a compelling and influential tone to sway opinions or encourage action.",
  engaging: "Capture and sustain interest with an interactive and dynamic tone.",
  formal: "Adopt a structured, respectful, and serious tone suitable for official communication.",
  respectful: "Show consideration, politeness, and deference in the tone.",
  instructive: "Provide guidance, direction, or step-by-step explanations in a helpful tone.",
  reflective: "Encourage introspection and thoughtfulness with a contemplative tone.",
  authoritative: "Project expertise, reliability, and command in the tone.",
  serious: "Adopt a somber, earnest, and no-nonsense tone for weighty matters.",
  provocative: "Challenge assumptions, spark curiosity, or incite strong reactions with a bold tone.",
  poetic: "Use a rhythmic, imaginative, and evocative tone to inspire or provoke emotion.",
  direct: "Be straightforward, to the point, and unambiguous in your tone.",
  supportive: "Convey encouragement, understanding, and solidarity in the tone.",
  approachable: "Break down barriers and make content feel accessible and welcoming.",
  diplomatic: "Balance tact and clarity to address sensitive matters without causing offense.",
  playful: "Incorporate a sense of fun, mischief, and creativity in the tone.",
  futuristic: "Adopt a forward-thinking, visionary tone that looks toward the possibilities of tomorrow.",
  romantic: "Express passion, beauty, and emotional intensity in the tone.",
  stoic: "Maintain a calm, composed, and resilient tone, focusing on reason over emotion.",
}
